In [1]:
import pandas as pd
import numpy as np

In [2]:
print("Python is working")

Python is working

In [4]:
df = pd.read_csv("../data/transactions.csv")

In [5]:
df

,date,description,amount,type,category,payment_method,account
0,2026-01-01,Salary,50000,Income,Salary,Bank Transfer,HDFC
1,2026-01-02,Rent,12000,Expense,Housing,Bank Transfer,HDFC
2,2026-01-03,Swiggy,450,Expense,Food,UPI,HDFC
3,2026-01-04,Amazon,1800,Expense,Shopping,UPI,HDFC
4,2026-01-05,Uber,320,Expense,Transport,UPI,HDFC
5,2026-01-06,Electricity Bill,1500,Expense,Utilities,UPI,HDFC
6,2026-01-07,Netflix,649,Expense,Entertainment,Card,HDFC
7,2026-01-08,Freelance Payment,8000,Income,Freelance,Bank Transfer,HDFC
8,2026-01-09,BigBasket,2300,Expense,Groceries,UPI,HDFC
9,2026-01-10,Pharmacy,750,Expense,Healthcare,UPI,HDFC

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            10 non-null     str
 1   description     10 non-null     str
 2   amount          10 non-null     int64
 3   type            10 non-null     str
 4   category        10 non-null     str
 5   payment_method  10 non-null     str
 6   account         10 non-null     str
dtypes: int64(1), str(6)
memory usage: 692.0 bytes

In [7]:
df.describe()

             amount
count     10.000000
mean    7776.900000
std    15330.676817
min      320.000000
25%      674.250000
50%     1650.000000
75%     6575.000000
max    50000.000000

In [8]:
df.columns

Index(['date', 'description', 'amount', 'type', 'category', 'payment_method',
       'account'],
      dtype='str')

In [9]:
df.shape

(10, 7)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["date"] = pd.to_datetime(df["date"])

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            10 non-null     datetime64[us]
 1   description     10 non-null     str
 2   amount          10 non-null     int64
 3   type            10 non-null     str
 4   category        10 non-null     str
 5   payment_method  10 non-null     str
 6   account         10 non-null     str
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 692.0 bytes

In [15]:
df.isnull().sum()

date              0
description       0
amount            0
type              0
category          0
payment_method    0
account           0
dtype: int64

In [16]:
df["type"].unique()

<StringArray>
['Income', 'Expense']
Length: 2, dtype: str

In [17]:
df["category"].unique()

<StringArray>
[       'Salary',       'Housing',          'Food',      'Shopping',
     'Transport',     'Utilities', 'Entertainment',     'Freelance',
     'Groceries',    'Healthcare']
Length: 10, dtype: str

In [18]:
df["payment_method"].unique()

<StringArray>
['Bank Transfer', 'UPI', 'Card']
Length: 3, dtype: str

In [19]:
df["account"].unique()

<StringArray>
['HDFC']
Length: 1, dtype: str

In [20]:
df["type"].value_counts()

type
Expense    8
Income     2
Name: count, dtype: int64

In [21]:
df.groupby("type")["amount"].sum()

type
Expense    19769
Income     58000
Name: amount, dtype: int64

In [22]:
df[df["type"]=="Expense"].groupby("category")["amount"].sum().sort_values(ascending=False)

category
Housing          12000
Groceries         2300
Shopping          1800
Utilities         1500
Healthcare         750
Entertainment      649
Food               450
Transport          320
Name: amount, dtype: int64

In [23]:
income= df[df["type"]=="Income"]["amount"].sum()
expenses= df[df["type"]=="Expense"]["amount"].sum()
savings= income-expenses
print("savings",savings)
print("expenses",expenses)
print("income",income)

savings 38231
expenses 19769
income 58000

In [27]:
saving_rate = ((savings/income)*100).round(2)
print("Saving percentage",saving_rate,"%")

Saving percentage 65.92 %

In [28]:
df["month"] = df["date"].dt.to_period("M")
df["month"].value_counts()

month
2026-01    10
Freq: M, Name: count, dtype: int64

In [29]:
df

,date,description,amount,type,category,payment_method,account,month
0,2026-01-01,Salary,50000,Income,Salary,Bank Transfer,HDFC,2026-01
1,2026-01-02,Rent,12000,Expense,Housing,Bank Transfer,HDFC,2026-01
2,2026-01-03,Swiggy,450,Expense,Food,UPI,HDFC,2026-01
3,2026-01-04,Amazon,1800,Expense,Shopping,UPI,HDFC,2026-01
4,2026-01-05,Uber,320,Expense,Transport,UPI,HDFC,2026-01
5,2026-01-06,Electricity Bill,1500,Expense,Utilities,UPI,HDFC,2026-01
6,2026-01-07,Netflix,649,Expense,Entertainment,Card,HDFC,2026-01
7,2026-01-08,Freelance Payment,8000,Income,Freelance,Bank Transfer,HDFC,2026-01
8,2026-01-09,BigBasket,2300,Expense,Groceries,UPI,HDFC,2026-01
9,2026-01-10,Pharmacy,750,Expense,Healthcare,UPI,HDFC,2026-01

In [30]:
df[df["type"]=="Expense"].groupby("payment_method")["amount"].sum().sort_values(ascending=False)

payment_method
Bank Transfer    12000
UPI               7120
Card               649
Name: amount, dtype: int64

In [31]:
df[df["type"]=="Expense"].groupby("description")["amount"].sum().sort_values(ascending=False)

description
Rent                12000
BigBasket            2300
Amazon               1800
Electricity Bill     1500
Pharmacy              750
Netflix               649
Swiggy                450
Uber                  320
Name: amount, dtype: int64

In [32]:
df.groupby(["month","type"])["amount"].sum()

month    type
2026-01  Expense    19769
         Income     58000
Name: amount, dtype: int64

In [33]:
df.sort_values("amount",ascending=False).head()

,date,description,amount,type,category,payment_method,account,month
0,2026-01-01,Salary,50000,Income,Salary,Bank Transfer,HDFC,2026-01
1,2026-01-02,Rent,12000,Expense,Housing,Bank Transfer,HDFC,2026-01
7,2026-01-08,Freelance Payment,8000,Income,Freelance,Bank Transfer,HDFC,2026-01
8,2026-01-09,BigBasket,2300,Expense,Groceries,UPI,HDFC,2026-01
3,2026-01-04,Amazon,1800,Expense,Shopping,UPI,HDFC,2026-01

In [34]:
df

,date,description,amount,type,category,payment_method,account,month
0,2026-01-01,Salary,50000,Income,Salary,Bank Transfer,HDFC,2026-01
1,2026-01-02,Rent,12000,Expense,Housing,Bank Transfer,HDFC,2026-01
2,2026-01-03,Swiggy,450,Expense,Food,UPI,HDFC,2026-01
3,2026-01-04,Amazon,1800,Expense,Shopping,UPI,HDFC,2026-01
4,2026-01-05,Uber,320,Expense,Transport,UPI,HDFC,2026-01
5,2026-01-06,Electricity Bill,1500,Expense,Utilities,UPI,HDFC,2026-01
6,2026-01-07,Netflix,649,Expense,Entertainment,Card,HDFC,2026-01
7,2026-01-08,Freelance Payment,8000,Income,Freelance,Bank Transfer,HDFC,2026-01
8,2026-01-09,BigBasket,2300,Expense,Groceries,UPI,HDFC,2026-01
9,2026-01-10,Pharmacy,750,Expense,Healthcare,UPI,HDFC,2026-01